config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  resources :users

  resources :products do
    resources :comments
  end
  
  resources :orders, only: [:index, :show, :create, :destroy]

  post 'payments/create'

  get '/about', to: 'simple_pages#about'

  get '/contact', to: 'simple_pages#contact'

  post 'simple_pages/thank_you'

  get '/home', to: 'simple_pages#landing_page'
  root 'simple_pages#landing_page'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App2</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>

  	<!--navbar starts here-->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <div class="home navbar-brand">
          <a href="/home">Home</a>
        </div> <!--end Home -->
      </div> <!--end navbar-header -->

        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="search_field"><%= form_with(url: products_path, method: 'get', local: true) do |form| %>
              <%= form.text_field :q, id: 'q', value: params[:q], placeholder:"E.g. longboard" %>
              <%= form.submit 'Search', class:"btn btn-sm" %>
               <% end %></li>
            <li class="nav_link"><%= link_to "About", about_path %></li>
            <li class="nav_link"><%= link_to "Products", products_path %></li>
            <li class="nav_link"><%= link_to "Orders", orders_path %></li>
            <li class="nav_link"><%= link_to "Contact", contact_path %></li>
            <li class="nav_link">
              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
              <% else %>
                <%= link_to('Login', new_user_session_path) %>
              <% end %>
            </li>
          </ul>
        </div> <!--end navbar collapse-->

      </div> <!-- end nav container-->
    </nav> <!-- end navbar-->
    
    

    <% if alert %>
      <p id="alert" class="alert alert-danger"><%= alert %></p>
    <% end %>

    <% if notice %>
      <p class="notice alert alert-info"><%= notice %></p>
    <% end %>

    <%= yield %>

    <footer class="site-footer">
      <div class="container-fluid social">
        <a href="https://www.instagram.com/tapea_berlin/" class="fa fa-instagram"></a>
        <a href="https://www.facebook.com/tabea.simon.1" class="fa fa-facebook"></a>
        <a href="https://www.linkedin.com/in/tabea-simon-7a254389/" class="fa fa-linkedin"></a>
      </div>

      <p>&copy; Tabea Simon 2017</p>

    </footer>
  </body>
</html>